export const siteConfig = {
  name: "Essence Treks Nepal",
  description: "Conquer the Roof of the World, One Step at a Time!",
  url: "https://essencetreksnepal.com",
  image: "/og.png",
  whatsAppNumber: "+9779804148802",
  phoneNumbers: [
    { phone: "+977-9804148802" },
    { tel: "+061-452788" },
    { tel2: "+061-452677" },
  ],
  email: "info@essencetreksnepal.com",
  openHours: "Sunday to Friday 9:00 AM to 5:00 PM Nepal Standard Time",
  experience: "20 years",
  address: {
    city: "Pokhara",
    street: "Khahare Chowk, Lakeside Rd",
    district: "Kaski",
    country: "Nepal",
    postalCode: "33700",
  },
  socials: {
    facebook: "https://www.facebook.com/essencetreksinnepal",
    instagram: "https://www.instagram.com/",
    twitter: "https://twitter.com/",
    youtube: "https://www.youtube.com/",
    tiktok: "https://www.tiktok.com/",
  },
  documents: {
    NATHM_Certificate: "/documents/nathm_certificate.webp",
    Tax_Certificate: "/documents/tax_certificate.webp",
    Identity_Card: "/documents/identity_card_for_trekking_guide.webp",
    Grading_Classification: "/documents/grading_classification.webp",
  },
};
